eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
    fetchRegistry: false
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka-server
# eureka-server: 8761-8763
# resource-server: 8764-8765
# project-server: 8766-8767
# junction-server: 8768-8769
server:
  port: 8761
#management:
#  context-path:  /